package com.jq.survey.dao.entity;

import java.util.Date;

public class RoleInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.ROLE_NAME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.CREATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.ROLE_ID
     *
     * @return the value of role_info.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.ROLE_ID
     *
     * @param roleId the value for role_info.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.ROLE_NAME
     *
     * @return the value of role_info.ROLE_NAME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.ROLE_NAME
     *
     * @param roleName the value for role_info.ROLE_NAME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.CREATE_TIME
     *
     * @return the value of role_info.CREATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.CREATE_TIME
     *
     * @param createTime the value for role_info.CREATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.UPDATE_TIME
     *
     * @return the value of role_info.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.UPDATE_TIME
     *
     * @param updateTime the value for role_info.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:18:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}