package com.jq.survey.dao.entity;

import java.util.Date;

public class RoleMenuDO extends RoleMenuKey {

	/**  */
	private static final long serialVersionUID = 6751021619138676843L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_menu.STAT
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_menu.CREATE_TIME
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_menu.UPDATE_TIME
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_menu.STAT
	 * @return  the value of role_menu.STAT
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_menu.STAT
	 * @param stat  the value for role_menu.STAT
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_menu.CREATE_TIME
	 * @return  the value of role_menu.CREATE_TIME
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_menu.CREATE_TIME
	 * @param createTime  the value for role_menu.CREATE_TIME
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_menu.UPDATE_TIME
	 * @return  the value of role_menu.UPDATE_TIME
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_menu.UPDATE_TIME
	 * @param updateTime  the value for role_menu.UPDATE_TIME
	 * @mbggenerated  Mon Jul 11 16:22:21 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}