package com.jq.survey.dao.entity;

public class RoleMenuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.MENU_ID
     *
     * @mbggenerated Mon Jul 11 16:22:21 CST 2016
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:22:21 CST 2016
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.MENU_ID
     *
     * @return the value of role_menu.MENU_ID
     *
     * @mbggenerated Mon Jul 11 16:22:21 CST 2016
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.MENU_ID
     *
     * @param menuId the value for role_menu.MENU_ID
     *
     * @mbggenerated Mon Jul 11 16:22:21 CST 2016
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.ROLE_ID
     *
     * @return the value of role_menu.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:22:21 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.ROLE_ID
     *
     * @param roleId the value for role_menu.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:22:21 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}