package com.jq.survey.dao.entity;

import java.util.Date;

/**
 * 
 * 
 * @author juqi
 * @version $Id: UserInfoDO.java, v 0.1 2016年7月11日 下午4:17:17 juqi Exp $
 */
public class UserInfoDO extends AbstractDO {
	
    /**  */
	private static final long serialVersionUID = -4958750289861851770L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_ID
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.LOGIN_NAME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.REAL_NAME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.PASSWORD
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.TEL
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.EMAIL
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DEPT
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.STAT
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.CREATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_ID
     *
     * @return the value of user_info.USER_ID
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_ID
     *
     * @param userId the value for user_info.USER_ID
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.LOGIN_NAME
     *
     * @return the value of user_info.LOGIN_NAME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.LOGIN_NAME
     *
     * @param loginName the value for user_info.LOGIN_NAME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.REAL_NAME
     *
     * @return the value of user_info.REAL_NAME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.REAL_NAME
     *
     * @param realName the value for user_info.REAL_NAME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.PASSWORD
     *
     * @return the value of user_info.PASSWORD
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.PASSWORD
     *
     * @param password the value for user_info.PASSWORD
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.TEL
     *
     * @return the value of user_info.TEL
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.TEL
     *
     * @param tel the value for user_info.TEL
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.EMAIL
     *
     * @return the value of user_info.EMAIL
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.EMAIL
     *
     * @param email the value for user_info.EMAIL
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.DEPT
     *
     * @return the value of user_info.DEPT
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.DEPT
     *
     * @param dept the value for user_info.DEPT
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.STAT
     *
     * @return the value of user_info.STAT
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.STAT
     *
     * @param stat the value for user_info.STAT
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ROLE_ID
     *
     * @return the value of user_info.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ROLE_ID
     *
     * @param roleId the value for user_info.ROLE_ID
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.CREATE_TIME
     *
     * @return the value of user_info.CREATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.CREATE_TIME
     *
     * @param createTime the value for user_info.CREATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDATE_TIME
     *
     * @return the value of user_info.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDATE_TIME
     *
     * @param updateTime the value for user_info.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 11 16:12:39 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}